const en = {
  intro:
    "Hi! I'm a Front-end developer with more than 4 years of experience. Focused on development and implementation on React, worked on B2B and B2C projects",
  education: "Education",
  university: "Belarusian State University of Informatics and Radioelectronics",
  faculty: "The Faculty of Information Technologies and Control",
  degree: "Bachelors degree",
  courses: "Courses",
  skills: "Skills",
  languages: "Programming languages",
  frameworks: "Frameworks",
  state: "State management",
  routing: "Routing",
  testing: "Testing libraries",
  bundlers: "Bundlers",
  ui: "UI libraries",
  styling: "Styling",
  modules: "modules",
  markup: "Markup",
  formatting: "Code formatting",
  methodologies: "Methodologies",
  versions: "Versions control",
  design: "Design tools",
  components: "Components libraries",
  utility: "Utility libraries",
  about: "About",
  portfolio: "Portfolio",
  name: "Pavel Osipau",
  job: "Frontend developer",
  links: "Links",
  demo: "Demo",
  repo: "Repository",
  petprojects: "Pet projects",
  bem: "BEM (for styling/structuring)",
  bundlersSetUp: "experience with set up project for both tools",
  rest: "... and a bit experience with Graphql, Node.js, Express, MobX, Postman, Insomnia, JWT Token, NativeScript, set up project using Webpack for Module Federation (Microfrontends)",
  english: "English",
  russian: "Russian",
  selectOption: "Select language",
  atlassian: "Atlassian",
  ide: "IDE",
  period: "Period",
  responsibility: "Key responsibilities",
};

const ru = {
  intro:
    "Привет! Я Фронтенд разработчик с опытом более чем 4 года. Основной фокус разработки и внедрения на React, работал над B2B и B2C проектами",
  education: "Образование",
  university: "Белорусский государственный университет информатики и радиоэлектроники",
  faculty: "Факультет информационных технологий и управления",
  degree: "Бакалавр",
  courses: "Курсы",
  skills: "Навыки",
  languages: "Языки программирования",
  frameworks: "Фреймворки",
  state: "Стейт менеджер",
  routing: "Роутинг",
  testing: "Библиотеки для тестирования",
  bundlers: "Сборщики",
  ui: "UI библиотеки",
  styling: "Стилизация",
  modules: "модули",
  markup: "Разметка",
  formatting: "Форматирование кода",
  methodologies: "Методологии",
  versions: "Контроль версий",
  design: "Дизайн-инструменты",
  components: "Библиотеки компонентов",
  utility: "Вспомогательные библиотеки",
  about: "Обо мне",
  portfolio: "Портфолио",
  name: "Павел Осипов",
  job: "Фронтенд разработчик",
  links: "Ссылки",
  demo: "Демо",
  repo: "Репозиторий",
  petprojects: "Учебные проекты",
  bem: "БЭМ (для стилизации/структуры)",
  bundlersSetUp: "опыт настройки проекта с каждым сборщиком",
  rest: "... и немного опыта с Graphql, Node.js, Express, MobX, Postman, Insomnia, JWT Token, NativeScript, настройка проекта с использованием Webpack для Module Federation (Микрофронтенды)",
  english: "Английский",
  russian: "Русский",
  selectOption: "Выберите язык",
  atlassian: "Atlassian",
  ide: "IDE",
  period: "Период",
  responsibility: "Ключевые задачи",
};

export const languages = { en, ru };
